# Generated by Django 3.2.12 on 2024-02-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total_movies', models.PositiveIntegerField()),
                ('genres', models.ManyToManyField(related_name='universe', to='base.Genre')),
            ],
        ),
    ]
