# Generated by Django 3.2.12 on 2024-02-16 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20240216_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='Djangoweb/cin'),
            preserve_default=False,
        ),
    ]
