# Generated by Django 3.2.12 on 2024-02-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_universe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='universe',
            name='image',
            field=models.ImageField(null=True, upload_to='universe/img'),
        ),
    ]
