# Generated by Django 3.2.12 on 2024-02-20 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_universe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='universe',
            name='rating',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
